# -*- coding: utf-8 -*-
"""DataCamp Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WisxyCrawo6LiHcK5Vb3AyzX4nuX0COO
"""

# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Commented out IPython magic to ensure Python compatibility.
link= 'https://drive.google.com/file/d/1lW_7vuu2KOwcgCGBrgq-y4ZORPMBmBYu/view?usp=sharing'
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt
from datetime import datetime
# %matplotlib inline
import plotly.express as px


# to get the id part of the file
id = link.split("/")[-2]
 
downloaded = drive.CreateFile({'id':id})
downloaded.GetContentFile('chocolate_bars.csv') 
 
df= pd.read_csv('chocolate_bars.csv',index_col='id')
df.head()

df.info()

df.describe()

df.duplicated().sum()

df.isnull().sum()

df["ingredients"].mode()

df["ingredients"].fillna(value = "B,S,C", inplace = True)

ni_mean=df['num_ingredients'].mean()
ni_mean

df["num_ingredients"].fillna(value = ni_mean, inplace = True)

df.isna().sum()

df.info()

"""PROJECT
You work at a specialty foods import company that wants to expand into gourmet chocolate bars. Your boss needs your team to research this market to inform your initial approach to potential suppliers.

After finding valuable chocolate bar ratings online, you need to explore if the chocolate bars with the highest ratings share any characteristics that could help you narrow your search for suppliers (e.g., cacao percentage, bean country of origin, etc.)

💪 Challenge
Create a report to summarize your research. Include:

1. What is the average rating by country of origin?
2. How many bars were reviewed for each of those countries?
3. Create plots to visualize findings for questions 1 and 2.
4. Is the cacao bean's origin an indicator of quality? 
5. [Optional] How does cocoa content relate to rating? What is the average cocoa content for bars with higher ratings (above 3.5)?
6. [Optional 2] Your research indicates that some consumers want to avoid bars with lecithin. Compare the average rating of bars with and without lecithin (L in the ingredients).
7. Summarize your findings.

1. What is the average rating by country of origin?
"""

One=df.groupby('bean_origin',as_index=False)['rating'].mean().sort_values(by='rating')
One
#convert to DataFrame
df1 = pd.DataFrame(One)
df1

"""2. How many bars were reviewed for each of those countries?"""

two=df.groupby('bean_origin', as_index=False)['review'].count().sort_values(by='review')
#convert it to DataFrame
df2=pd.DataFrame(two)
df2

"""3. Create plots to visualize findings for questions 1 and 2.

A
"""

plt.subplots(figsize=(15, 15))
p=sns.barplot(x='rating',y='bean_origin',data=df1, orient="h", color='grey')
p.set(xlabel ="RATING", ylabel = "BEAN ORIGIN", title ='VISUALIZATION OF RATING AGANIST BEAN ORIGIN')
plt.show()

"""How many bars were reviewed for each of those countries?"""

#px.subplots(figsize=(15, 15))
fig= px.funnel(df2, x='review', y='bean_origin', 
               labels={'review':'REVIEW', 'bean_origin': 'BEAN ORIGIN'},
               title='Visualization of Review against Bean Origin')
#fig.set(xlabel ="REVIEW", ylabel = "BEAN ORIGIN", title ='VISUALIZATION OF REVIEW AGANIST BEAN ORIGIN')

fig.show()

"""B"""

plt.subplots(figsize=(15,15))
q=sns.barplot(x='review',y='bean_origin',data=df2, orient="h", color='green')
q.set(xlabel ="REVIEW", ylabel = "BEAN ORIGIN", title ='VISUALIZATION OF REVIEW AGANIST BEAN ORIGIN')
plt.show()

"""4. Is the cacao bean's origin an indicator of quality? """

df['bean_origin'].count()=='cocao'

"""Since, cacao bean"s origin can not be found. Therefore, it does not exist in the dataset.

5. How does cocoa content relate to rating? 
What is the average cocoa content for bars with higher ratings (above 3.5)?

A
"""

three=df.groupby('cocoa_percent', as_index=False)['rating'].count()
#convert it to DataFrame
df3=pd.DataFrame(three)
df3

r=sns.heatmap(df3.corr(), vmin=-1, vmax=1, annot=True, cmap='BrBG')
r.set_title('Correlation Heatmap of Cocoa Percent and Rating', fontdict={'fontsize':18}, pad=12)

"""B. What is the average cocoa content for bars with higher ratings (above 3.5)?"""

#streamline the dataset to participate that have above 3.5 as rating
four=df.loc[df['rating'] > 3.5]
four
#get their average
df4=four.groupby('rating',as_index=False)['cocoa_percent'].mean()
df4

"""6. Your research indicates that some consumers want to avoid bars with lecithin. 
Compare the average rating of bars with and without lecithin (L in the ingredients).
"""

df.loc[df['ingredients'] == '%L%']

df['ingredients'].unique()



